azure: Remove custom key directory
Otherwise, the following happens:
ERROR: Deployment failed. Correlation ID: d5964a8d-a6d6-468b-a0d0-984d8347a1a2. {
  "error": {
    "code": "InvalidParameter",
    "message": "Destination path for SSH public keys is currently limited to its default value /home/ubuntu/.ssh/authorized_keys  due to a known issue in Linux provisioning agent.",
    "target": "linuxConfiguration.ssh.publicKeys.path"
  }
}